sudo: false
language: cpp
compiler:
  - g++

install:
   - sudo apt-get install libgtest-dev


script:
  - cd tests
  - g++ -Igtest-1.7.0/include -Igtest-1.7.0 -c gtest-1.7.0/src/gtest-all.cc
  - ar -rv libgtest.a gtest-all.o
  - make
  - ls
  - text_executable
